server {
    listen 80;
    listen [::]:80;
    server_name www.qianfamily.online;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html/qianfamily.online/out;
        try_files $uri =404;
    }

    location / {
        return 301 https://qianfamily.online$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name qianfamily.online;

    root /usr/share/nginx/html/qianfamily.online/out;
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.qianfamily.online;

    ssl_certificate /etc/letsencrypt/live/qianfamily.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qianfamily.online/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        return 301 https://qianfamily.online$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name qianfamily.online;

    root /usr/share/nginx/html/qianfamily.online/out;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/qianfamily.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qianfamily.online/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        try_files $uri $uri/ $uri.html /index.html =404;
    }
}
